import daiImg from '../assets/image/coins/dai.svg';
import usdcImg from '../assets/image/coins/usdc.svg';
import usdtImg from '../assets/image/coins/usdt.svg';
import batImg from '../assets/image/coins/bat.svg';
import ethImg from '../assets/image/coins/eth.svg';
import uniImg from '../assets/image/coins/uni.svg';
import wbtcImg from '../assets/image/coins/wbtc.svg';
import zrxImg from '../assets/image/coins/zrx.svg';

export const marketData = [
  {
    name: 'DAI',
    img: daiImg,
    market_size: 14300,
    liquidity: 12000,
    total_borrowed: 2300,
    deposit_apy: 0.03,
    variable_borrow_apr: 0.43,
    stable_borrow_apr: 9.21,
    asset_price: 1,
    wallet_balance: 8000,
    protocol_balance: 0,
    collateral: true,
    isVariable: true,
  },
  {
    name: 'USDC',
    img: usdcImg,
    market_size: 32000,
    liquidity: 27200,
    total_borrowed: 4800,
    deposit_apy: 1.63,
    variable_borrow_apr: 2.27,
    stable_borrow_apr: 7.32,
    asset_price: 1,
    wallet_balance: 4000,
    collateral: false,
    isVariable: false,
  },
  {
    name: 'USDT',
    img: usdtImg,
    market_size: 9800,
    liquidity: 6600,
    total_borrowed: 3200,
    deposit_apy: 0.02,
    variable_borrow_apr: 0.04,
    stable_borrow_apr: 5.02,
    asset_price: 1,
    wallet_balance: 9000,
    protocol_balance: 0,
    collateral: true,
    isVariable: true,
  },
  {
    name: 'BAT',
    img: batImg,
    market_size: 6420,
    liquidity: 5120,
    total_borrowed: 1300,
    deposit_apy: 0.95,
    variable_borrow_apr: 4.31,
    stable_borrow_apr: 9.15,
    asset_price: 0.24,
    wallet_balance: 3208,
    protocol_balance: 0,
    collateral: true,
    isVariable: true,
  },
  {
    name: 'ETH',
    img: ethImg,
    market_size: 3600,
    liquidity: 2100,
    total_borrowed: 1500,
    deposit_apy: 93.27,
    variable_borrow_apr: 105.15,
    stable_borrow_apr: 107.15,
    asset_price: 1157.39,
    wallet_balance: 2340,
    protocol_balance: 0,
    collateral: false,
    isVariable: false,
  },
  {
    name: 'UNI',
    img: uniImg,
    market_size: 7800,
    liquidity: 5500,
    total_borrowed: 2300,
    deposit_apy: 0.67,
    variable_borrow_apr: 0.31,
    stable_borrow_apr: 7.53,
    asset_price: 7.09,
    wallet_balance: 6700,
    protocol_balance: 0,
    collateral: true,
    isVariable: true,
  },
  {
    name: 'WBTC',
    img: wbtcImg,
    market_size: 14300,
    liquidity: 12000,
    total_borrowed: 2300,
    deposit_apy: 0.01,
    variable_borrow_apr: 0.30,
    stable_borrow_apr: 0.38,
    asset_price: 35996.93,
    wallet_balance: 5800,
    protocol_balance: 0,
    collateral: true,
    isVariable: true,
  },
  {
    name: 'ZRX',
    img: zrxImg,
    market_size: 6300,
    liquidity: 1200,
    total_borrowed: 5100,
    deposit_apy: 0.02,
    variable_borrow_apr: 0.68,
    stable_borrow_apr: 3.97,
    asset_price: 0.49,
    wallet_balance: 0,
    protocol_balance: 0,
    collateral: false,
    isVariable: false,
  },
];
